"""added endereco

Revision ID: 3e943907e792
Revises: ed35903089b5
Create Date: 2023-12-08 15:20:26.788529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e943907e792'
down_revision = 'ed35903089b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Endereco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('rua', sa.String(length=400), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('complemento', sa.String(length=255), nullable=True),
    sa.Column('bairro', sa.String(length=300), nullable=False),
    sa.Column('cidade', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.Column('cep', sa.Integer(), nullable=False),
    sa.Column('data_inclusao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Endereco')
    # ### end Alembic commands ###
