"""added destaque col

Revision ID: ce83eeef7d12
Revises: 3e943907e792
Create Date: 2023-12-09 16:26:35.159642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce83eeef7d12'
down_revision = '3e943907e792'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Produto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destaque', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Produto', schema=None) as batch_op:
        batch_op.drop_column('destaque')

    # ### end Alembic commands ###
