"""added carrinho favs

Revision ID: ed35903089b5
Revises: 2d30d8f0593f
Create Date: 2023-11-29 17:01:45.872577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed35903089b5'
down_revision = '2d30d8f0593f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Favoritos',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_produto', sa.Integer(), nullable=False),
    sa.Column('data_inclusao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_produto'], ['Produto.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_usuario', 'id_produto')
    )
    op.create_table('Carrinho',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_estoque', sa.Integer(), nullable=False),
    sa.Column('qtd', sa.Integer(), nullable=False),
    sa.Column('data_inclusao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_estoque'], ['ProdutoEstoque.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_usuario', 'id_estoque')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Carrinho')
    op.drop_table('Favoritos')
    # ### end Alembic commands ###
